# Generated by Django 5.2.5 on 2025-09-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userchat_usermessage'),
        ('products', '0005_alter_shoprating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userchat',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together={('user1', 'user2', 'product')},
        ),
    ]
