# Generated by Django 5.2.5 on 2025-09-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='checkout_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
