# Generated by Django 5.2.5 on 2025-09-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_checkout_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bank_account_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='paypal_client_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
