# Generated by Django 5.2.5 on 2025-09-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_bank_account_info_shop_paypal_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='order_reminder_period',
            field=models.CharField(choices=[('8h', '8 Hours'), ('12h', '12 Hours'), ('1d', '1 Day'), ('2d', '2 Days'), ('3d', '3 Days')], default='1d', max_length=3),
        ),
    ]
