# Generated by Django 5.2.5 on 2025-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='show_stock_to_customers',
            field=models.BooleanField(default=False),
        ),
    ]
