# Generated by Django 5.2.5 on 2025-09-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='guest_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest_phone',
            new_name='customer_phone',
        ),
    ]
