# Generated by Django 5.2.5 on 2025-09-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_variant_name_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variant',
            new_name='product_variant',
        ),
    ]
