# Generated by Django 5.2.5 on 2025-09-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productrating_shoprating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home & Garden', 'Home & Garden'), ('Sports', 'Sports'), ('Books', 'Books'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Food', 'Food'), ('Automotive', 'Automotive'), ('Health', 'Health'), ('Other', 'Other')], max_length=50),
        ),
    ]
