# Generated by Django 5.2.5 on 2025-09-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home & Garden', 'Home & Garden'), ('Sports', 'Sports'), ('Books', 'Books'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Food', 'Food'), ('Automotive', 'Automotive'), ('Health', 'Health'), ('Other', 'Other')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
