# Generated by Django 5.2.5 on 2025-09-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoprating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shoprating',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shoprating',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.DeleteModel(
            name='ShopRating',
        ),
    ]
