# Generated by Django 5.2.5 on 2025-09-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_shoprating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'name')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_adjustment',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='value',
        ),
    ]
